services:
  server:
    image: "docker.io/chengwork/grpc-dotnet-racer-server:0.6"
    networks:
      - network_grpc
    ports:
      - "5001:5001"
  client:
    image: "docker.io/chengwork/grpc-dotnet-racer-client:0.6"
    networks:
      - network_grpc
    depends_on:
      server:
        condition: service_started
networks:
  network_grpc:
    name: network_grpc
    driver: bridge
